name: Build and Upload Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang lld python2 llvm git make gcc flex bison bc libssl-dev ccache libncurses5-dev libncursesw5-dev libtinfo5 cmake python3
      - name: Build Project
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "zeroXone-github"
          rm -rf KernelSU
          git add .
          git commit -m "Remove Folder"
          git push origin
